spring:
  application:
    name: Beauty_back
  datasource:
    url: jdbc:mysql://localhost:3306/beauty?useSSL=false&serverTimezone=UTC
    username: root
    password: sharkguragura
    driver-class-name: com.mysql.cj.jdbc.Driver

